# Generated by Django 2.1.2 on 2018-12-03 00:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_auto_20181203_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Profile',
        ),
    ]
